name: tukigg
description: Find the best game deals from many stores in one app.
publish_to: "none"
version: 1.0.3+5

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  page_transition: ^2.0.9
  easy_localization: ^3.0.1
  shared_preferences: ^2.1.1
  font_awesome_flutter: ^10.4.0
  share_plus: ^7.0.0
  global_configuration: ^2.0.0-nullsafety.1
  url_launcher: ^6.1.10
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  package_info_plus: ^4.0.0
  animated_text_kit: ^4.2.2
  text_scroll: ^0.2.0
  lottie: ^2.3.2
  workmanager: ^0.5.1
  flutter_local_notifications: ^14.0.0+2
  path_provider: ^2.0.15
  permission_handler: ^10.2.0

  #Architecture
  http: ^0.13.6
  dartz: ^0.10.1
  get_it: ^7.5.0
  provider: ^6.0.5
  flutter_bloc: ^8.1.2
  json_annotation: ^4.8.1
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  dart_code_metrics: ^5.7.3

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/config/
    - assets/images/
    - assets/images/general/

  fonts:
    - family: Catamaran
      fonts:
        - asset: assets/fonts/Catamaran/Catamaran-Light.ttf
          weight: 300
        - asset: assets/fonts/Catamaran/Catamaran-Regular.ttf
          weight: 400
        - asset: assets/fonts/Catamaran/Catamaran-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Catamaran/Catamaran-ExtraBold.ttf
          weight: 800
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
