name: tukigg
description: Find the best game deals from many stores in one app.
publish_to: 'none'
version: 1.1.0+7

environment:
    sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  page_transition: ^2.2.1
  easy_localization: ^3.0.7+1
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  share_plus: ^11.0.0
  global_configuration: ^2.0.0-nullsafety.1
  url_launcher: ^6.3.2
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  package_info_plus: ^8.3.0
  animated_text_kit: ^4.2.3
  text_scroll: ^0.2.0
  lottie: ^3.3.1
  workmanager: ^0.8.0
  flutter_local_notifications: ^19.3.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1

  #Architecture
  http: ^1.4.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  provider: ^6.1.5
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true

  assets:
    - assets/lang/
    - assets/config/
    - assets/images/
    - assets/images/general/

  fonts:
    - family: Catamaran
      fonts:
        - asset: assets/fonts/Catamaran/Catamaran-Light.ttf
          weight: 300
        - asset: assets/fonts/Catamaran/Catamaran-Regular.ttf
          weight: 400
        - asset: assets/fonts/Catamaran/Catamaran-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Catamaran/Catamaran-ExtraBold.ttf
          weight: 800
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 400
